// <auto-generated />
using System;
using Frodo.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Frodo.Infra.Data.Migrations
{
    [DbContext(typeof(FrodoContext))]
    [Migration("20250525173402_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frodo.Pets.Domain.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherDuration")
                        .HasColumnType("text");

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.Property<DateTime>("TakenIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Medications", "Pets");
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FavoriteFood")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MicrochipId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Pets", "Pets");
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Tutors", "Pets");
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Laboratory")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Vaccines", "Pets");
                });

            modelBuilder.Entity("Frodo.Pets.Domain.VaccineDate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PetVaccineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RevaccinateIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("VaccinationIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("VaccineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.ToTable("VaccineDates", "Pets");
                });

            modelBuilder.Entity("Frodo.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "Users");
                });

            modelBuilder.Entity("Frodo.Users.Domain.UserVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserVerificationTokens", "Users");
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Medication", b =>
                {
                    b.HasOne("Frodo.Pets.Domain.Pet", null)
                        .WithMany("Medications")
                        .HasForeignKey("PetId");
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Tutor", b =>
                {
                    b.HasOne("Frodo.Pets.Domain.Pet", null)
                        .WithMany("Tutors")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Vaccine", b =>
                {
                    b.HasOne("Frodo.Pets.Domain.Pet", null)
                        .WithMany("Vaccines")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Frodo.Pets.Domain.VaccineDate", b =>
                {
                    b.HasOne("Frodo.Pets.Domain.Vaccine", null)
                        .WithMany("Dates")
                        .HasForeignKey("VaccineId");
                });

            modelBuilder.Entity("Frodo.Users.Domain.UserVerificationToken", b =>
                {
                    b.HasOne("Frodo.Users.Domain.User", null)
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Pet", b =>
                {
                    b.Navigation("Medications");

                    b.Navigation("Tutors");

                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("Frodo.Pets.Domain.Vaccine", b =>
                {
                    b.Navigation("Dates");
                });

            modelBuilder.Entity("Frodo.Users.Domain.User", b =>
                {
                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
